#name: front-main-deploy
#
#on:
#  push: # 적용될 액션
#    branches: main # 적용될 브랜치
#    paths:
#      - "resources/**" # workflow에서 적용될 path
#
#defaults:
#  run:
#    working-directory: ./src/main/resources # workflow에서 default working directory
#
#jobs:
#  deploy:
#    runs-on: ubuntu-latest # 인스턴스 OS
#    steps:
#      - name: Checkout source code
#        uses: actions/checkout@master # 워크플로에서 액세스할 수 있도록 에서 저장소를 체크아웃
#
#      - name: Install Dependencies
#        run: yarn
#
#      - name: Build
#        run: yarn build
#
#      - name: S3 Deploy
#        run: aws s3 sync ./dist s3://${{ secrets.BUCKET_NAME }}/ --acl bucket-owner-full-control # s3 이름 2021-cvi
#        env:
#          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          AWS_REGION: 'ap-northeast-2'

name: my-front
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: 'ap-northeast-2'

    steps:
      - name: Checkout source code.
        uses: actions/checkout@master

      - name: Upload binary to S3 bucket
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --exclude '*' --include 'index.html'
        env:
          AWS_S3_BUCKET: ${{ secrets.BUCKET_NAME }}

      - name: Invalidate cache CloudFront
        uses: chetan/invalidate-cloudfront-action@master
        env:
          DISTRIBUTION: ${{ secrets.DISTRIBUTION_ID }}
          PATHS: 'resources/**'
        continue-on-error: true